apiVersion: v1
kind: Service
metadata:
  name: loan-validator-portal-service
  namespace: default
  labels:
    app: loan-validator-portal
spec:
  type: LoadBalancer
  selector:
    app: loan-validator-portal
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
