apiVersion: v1
kind: ConfigMap
metadata:
  name: government-api-config
  namespace: default
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "government_loan_db"
  PORT: "8081"
